sudo: required
services:
  - docker

before_install:
  - docker build -t forceedge01/docker-test:latest -f Dockerfile.dev .

script:
  - docker run forceedge01/docker-test:latest npm run test -- --coverage --watchAll=false

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-test"
  env: "DockerTest-env"
  bucket_name: "elasticbeanstalk-us-east-2-946151971072"
  bucket_path: "docker-test"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
